# Generated by Django 3.2.20 on 2024-07-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='memo',
            field=models.TextField(default=None, null=True),
        ),
    ]
